### ISSUE TITLE
[propose-update] unable to push to dist-git: [remote rejected] (pre-receive hook declined)

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#248]
```python
  File "packit_service/worker/tasks.py", line 42, in process_message
    return SteveJobs().process_message(event=event, topic=topic)
  File "packit_service/worker/jobs.py", line 268, in process_message
    jobs_results = self.process_jobs(event_object)
  File "packit_service/worker/jobs.py", line 128, in process_jobs
    handlers_results[job.job.value] = handler.run()
  File "packit_service/worker/github_handlers.py", line 196, in run
    create_pr=False,
  File "packit/api.py", line 271, in sync_release
    self.dg.push(refspec=f"HEAD:{dist_git_branch}")
  File "packit/base_git.py", line 408, in push
    f"We were unable to push to dist-git: {pi.summary}."
```

https://sentry.io/organizations/red-hat-0p/issues/1345272053

**Comment by jpopelka** [comment]
It actually might have the same cause as https://sentry.io/organizations/red-hat-0p/issues/1345288042 and should be fixed permanently once #215 gets into prod

**Comment by jpopelka** [comment]
[Still happens](https://sentry.io/organizations/red-hat-0p/issues/1375151890)

**Comment by lachmanfrantisek** [comment]
No sentry issues are still present. Let's close and see if it occurs again.

**Comment by johannbg** [comment]
It occured again https://github.com/dracutdevs/dracut/issues/1713
