### ISSUE TITLE
Bad source: No such file or directory while SRPM build

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/packit-service#344]
Occurs in: https://github.com/packit-service/systemd-rhel8-flock/pull/9
```
An unexpected error occurred when creating the SRPM: Command failed (rc=1, reason={"metadata":{},"status":"Failure","message":"command terminated with non-zero exit code: Error executing in Docker Container: 1","reason":"NonZeroExitCode","details":{"causes":[{"reason":"ExitCode","message":"1"}]}})
error: Bad source: ./systemd-rhel8-flock-c631c3d.tar.gz: No such file or directory
```
Sentry error: https://sentry.io/organizations/red-hat-0p/issues/1450362049/

On the same PR this error can be seen: - moved to separate issue https://github.com/packit-service/packit-service/issues/363
```
Exception: ['oc', 'cp', 'packit-prod-sandbox/docker-io-usercont-sandcastle-20200120-092200074382:/tmp/tmp.eEg5uebLzE/t.tar.gz', '/tmp/tmpzbwcasvo'] failed with 'error: tmp/tmp.eEg5uebLzE/t.tar.gz no such file or directory\n'
```
https://sentry.io/organizations/red-hat-0p/issues/1456648052/~~

**Comment by TomasTomecek** [comment]
and I really thought I fixed this in https://github.com/packit-service/packit/pull/667

**Comment by dhodovsk** [comment]
Occurred here: https://github.com/pcahyna/rear/pull/1

**Comment by dhodovsk** [comment]
It seems it is still a problem for repositories that have the specfile stored in a subdirectory.

Reproducer PR - https://github.com/packit-service/hello-world/pull/78
